Dual Weapon Defense: Adjusted parry chance limit < 90% (parries are never guaranteed)
Dual Weapon Mastery: Adjusted parry chance limit < 90% (parries are never guaranteed)

Feint: Target Pinned and Dazed. Defensive buff includes one extra parry and reduced parry fail chance.  Removed extra deflect damage from parry.

Lunge: Reduced stamina cost.

Disengage:  Updated interface for target grid.  Added AI functions.  Not usable while pinned.  Requires a seen target.  Heavy armour (through fatigue) penalizes range and speed boost.

Evasion: Remove projectile missile spread.

Trained Reactions: vs. previous non-Reflex Defense like version: Restore stamina cost.  Simplify defense mechanics.  Added min damage limit of 5% of max life.

Terror: Victim must be able to see the talent user.

Marked for Death: Will not go on cooldown if the target is unreachable.